### ISSUE TITLE
[Android Bootcamp] Prework - Review my app

### ISSUE THREAD

**Issue by sammsiontir** [sammsiontir/SimpleToDo#1]
My basic todo app is complete, please review. Also, I have a question about Toolbar. In your video, there is no toolbar in blank activity, but it is default created in my app. I hit some error if I removed it form layout and java. Did I some setup wrong? /cc @codepathreview @codepath

**Comment by nesquena** [comment]
Hi Cheng-Fu,

Thanks for applying and submitting your pre-work. Based on your LinkedIn it is unclear if you meet the [selection criteria for participating in the course](http://courses.codepath.com/snippets/intro_to_android/selection_criteria). In particular:
- Within past 3 years have been employed as a software engineer, team lead, technical founder, VPE
- 2+ years of professional software development experience (average participant has 5+ years)
- Sustained professional software experience at companies involving shipping production code strongly preferred

Can you review that and let me know if you can confirm that you meet the requirements? If not, I can add you as a "remote self-paced observer" so you can still have access to the curriculum and learn at your pace. In the meantime, you should also check out the [resources we provide here](http://courses.codepath.com/snippets/intro_to_android/email_faq#heading-i-dont-have-much-or-any-professional-software-development-experience-how-can-codepath-help-me).

**Comment by sammsiontir** [comment]
I currently work in a hardware team at Apple. Though it's a hardware team, my job is using C++, perl, assembly to develop test frameworks and test generators. 
I was a research assistant in Academia Sinica for two years. I used C (with openCV library), matlab to develop face identification system to implement my manager's research. 
When I was a graduated student, I was also an software intern at Synopsys. It is software company that sells electronic design automation products. 
I believe I am qualify as a software engineer, which meet the first and second criteria. Indeed I don't have any experience as a frond-end engineer, but I can learn it fast. Thank you.
