### ISSUE TITLE
[Android Bootcamp] Prework - Review my app #2

### ISSUE THREAD

**Issue by sammsiontir** [sammsiontir/SimpleToDo#2]
My prework is complete. I achieved all the required and suggested features. I also improved the UI and added icons for all bottoms. Since you didn't answer my previous reply, I want to clarify that I meet all the requirements again. I am working in a hardware team, but it's a software position. My previous jobs are also software related. Thank you. /cc @codepathreview @codepath

**Comment by nesquena** [comment]
Great, thanks for the update and for the clarifications. We will be deciding final admittance for applicants in the next few days, thanks for your patience.
